#ifndef CPP_APPS_CONSTANT
#define CPP_APPS_CONSTANT

#define SECOND_SEM "SECOND_SEM"
#define MID_TERM "MID_TERM"
#define FINAL_SEM "FINAL_SEM"
#define DEVELOPERS_INFORMATION "DEVELOPERS_INFORMATION"
#define SUMPPLEMENTARY_APP "SUMPPLEMENTARY_APP"

#endif